name: 🛠️ Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: 🧪 Сборка APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v4

      - name: ☕ Установка Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: 🧰 Доступ к правам на gradlew
        run: chmod +x ./gradlew

      - name: 🧱 Сборка Release APK
        run: ./gradlew assembleRelease

      - name: 📦 Сохранение APK как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
